print('======== DESAFIO 06 ========')
print('')
n = float(input('Informe um número para saber seu dobro, triplo e raiz quadrada:'))
print('')
print('O dobro de {} é: {}'.format(n, n*2))
print('O triplo de {} é: {}'.format(n, n*3))
print('A raiz quadrada de {} é: {:.2f}'.format(n, n**(1/2)))